/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Paula
 */
public class MenuAdminView extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdminView
     */
    public MenuAdminView() {
        initComponents();
        setLocationRelativeTo(null);  // Centra la ventana en la pantalla
        setTitle("Menu Principal Admin");
    }

    public JButton getBtn_biblioteca() {
        return btn_biblioteca;
    }

    public JButton getBtn_bibliotecario() {
        return btn_bibliotecario;
    }

    public JButton getBtn_consultas() {
        return btn_consultas;
    }

    public JButton getBtn_libros() {
        return btn_libros;
    }

    public JButton getBtn_prestamos() {
        return btn_prestamos;
    }

    public JButton getBtn_sanciones() {
        return btn_sanciones;
    }

    public JButton getBtn_socios() {
        return btn_socios;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_biblioteca = new javax.swing.JButton();
        btn_bibliotecario = new javax.swing.JButton();
        btn_consultas = new javax.swing.JButton();
        btn_sanciones = new javax.swing.JButton();
        btn_libros = new javax.swing.JButton();
        btn_socios = new javax.swing.JButton();
        btn_prestamos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("MENU");

        btn_biblioteca.setBackground(new java.awt.Color(0, 153, 153));
        btn_biblioteca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_biblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btn_biblioteca.setText("GESTIONAR BIBLIOTECA");

        btn_bibliotecario.setBackground(new java.awt.Color(0, 153, 153));
        btn_bibliotecario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_bibliotecario.setForeground(new java.awt.Color(255, 255, 255));
        btn_bibliotecario.setText("GESTIONAR BIBLIOTECARIO");

        btn_consultas.setBackground(new java.awt.Color(0, 153, 153));
        btn_consultas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_consultas.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultas.setText("CONSULTAS");

        btn_sanciones.setBackground(new java.awt.Color(0, 153, 153));
        btn_sanciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_sanciones.setForeground(new java.awt.Color(255, 255, 255));
        btn_sanciones.setText("SANCIONES");

        btn_libros.setBackground(new java.awt.Color(0, 153, 153));
        btn_libros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_libros.setForeground(new java.awt.Color(255, 255, 255));
        btn_libros.setText("GESTIONAR LIBROS");

        btn_socios.setBackground(new java.awt.Color(0, 153, 153));
        btn_socios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_socios.setForeground(new java.awt.Color(255, 255, 255));
        btn_socios.setText("GESTIONAR SOCIOS");

        btn_prestamos.setBackground(new java.awt.Color(0, 153, 153));
        btn_prestamos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_prestamos.setForeground(new java.awt.Color(255, 255, 255));
        btn_prestamos.setText("PRÉSTAMOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_prestamos)
                    .addComponent(btn_sanciones)
                    .addComponent(btn_consultas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_socios)
                            .addComponent(btn_libros))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_biblioteca)
                        .addGap(132, 132, 132))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_bibliotecario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(btn_bibliotecario)
                .addGap(31, 31, 31)
                .addComponent(btn_biblioteca)
                .addGap(31, 31, 31)
                .addComponent(btn_socios)
                .addGap(33, 33, 33)
                .addComponent(btn_libros)
                .addGap(32, 32, 32)
                .addComponent(btn_sanciones)
                .addGap(33, 33, 33)
                .addComponent(btn_prestamos)
                .addGap(40, 40, 40)
                .addComponent(btn_consultas)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_biblioteca;
    private javax.swing.JButton btn_bibliotecario;
    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton btn_libros;
    private javax.swing.JButton btn_prestamos;
    private javax.swing.JButton btn_sanciones;
    private javax.swing.JButton btn_socios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
